<img src="img/Marca-ITBA-Color-ALTA.png" width="200">

# Master en Management & Analytics

## Programación para el Análisis de Datos

## Clase 2 - práctica resuelta


In [1]:
import numpy as np
import pandas as pd
import os
print(os.getcwd())

c:\Users\MEC\Documents\itba\analisis_datos\repaso


### Ejercicio 1

Escribir una función que sume todos los multiplos de 7 y 9 menores a 100

In [2]:
def sum_m7_m9(lista: list):
    lista = lista[lista < 100]
    lista = lista[(lista % 7 == 0) | (lista % 9 == 0)]
    print(lista)
    lista = np.sum(lista)
    return lista
    
a = np.arange(1, 200)

sum_m7_m9(a)

[ 7  9 14 18 21 27 28 35 36 42 45 49 54 56 63 70 72 77 81 84 90 91 98 99]


1266

### Ejercicio 2

Crear una función que calcule la media movil con una ventana de largo 3.

**pista:**
- $$SMA = \frac{A_{n-2} + A_{n-1} + A_{n}}{3}$$
- Método [*cumsum*](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

In [3]:
def moving_average(arr, n=3):
    
    mav = arr.cumsum()
    
    print(mav[n:])
    print(mav[:-n])
    mav[n:] = mav[n:] - mav[:-n]
    
    return mav[n - 1:] / n

a = np.arange(1,11)

moving_average(a, 3)

[10 15 21 28 36 45 55]
[ 1  3  6 10 15 21 28]


array([2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
def media_movil_3(lista: list):
    print(lista)
    lista = [sum(lista[i-3:i])/3 for i in lista[2:]]
    #lista = lista[::]
    return lista
    
a = np.arange(1,11)

media_movil_3(a)

[ 1  2  3  4  5  6  7  8  9 10]


[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

### Ejercicio 3


* Crear un dataframe que contenga la siguiente información:


|    |  Nombre             | Posición | Número
|---:|:---------           | :----    |:----
|  0 | Nery Pumpido        | ARQ      | 18
|  1 | José Cuciuffo       | DEF      | 9
|  2 | José Luis Brown     | DEF      | 5
|  3 | Oscar Ruggeri       | DEF      | 19
|  4 | Sergio Batista      | MED      | 2
|  5 | Ricardo Giusti      | MED      | 14
|  6 | Jorge Burruchaga    | MED      | 7
|  7 | Héctor Enrique      | MED      | 12
|  8 | Julio Olarticoechea | MED      | 16
|  9 | Jorge Valdano       | DEL      | 11
|  10| Diego Maradona      | DEL      | 10


In [5]:
jugadores = [
    {"Nombre": "Nery Pumpido", "Posición": "ARQ", "Número": 18},
    {"Nombre": "José Cuciuffo", "Posición": "DEF", "Número": 9},
    {"Nombre": "José Luis Brown", "Posición": "DEF", "Número": 5},
    {"Nombre": "Oscar Ruggeri", "Posición": "DEF", "Número": 19},
    {"Nombre": "Sergio Batista", "Posición": "MED", "Número": 2},
    {"Nombre": "Ricardo Giusti", "Posición": "MED", "Número": 14},
    {"Nombre": "Jorge Burruchaga", "Posición": "MED", "Número": 7},
    {"Nombre": "Héctor Enrique", "Posición": "MED", "Número": 12},
    {"Nombre": "Julio Olarticoechea", "Posición": "MED", "Número": 16},
    {"Nombre": "Jorge Valdano", "Posición": "DEL", "Número": 11},
    {"Nombre": "Diego Maradona", "Posición": "DEL", "Número": 10},
]

df = pd.DataFrame(jugadores)
display(df)

Nombre Posición  Número
0          Nery Pumpido      ARQ      18
1         José Cuciuffo      DEF       9
2       José Luis Brown      DEF       5
3         Oscar Ruggeri      DEF      19
4        Sergio Batista      MED       2
5        Ricardo Giusti      MED      14
6      Jorge Burruchaga      MED       7
7        Héctor Enrique      MED      12
8   Julio Olarticoechea      MED      16
9         Jorge Valdano      DEL      11
10       Diego Maradona      DEL      10

### Ejercicio 4

* A partir del dataframe creado, generar una serie con el nombre de los mediocampistas

**Ayuda:** usar una máscara booleana

In [6]:
df_med = pd.Series(df["Nombre"][df["Posición"]=="MED"])
display(df_med)
print(type(df_med))

4         Sergio Batista
5         Ricardo Giusti
6       Jorge Burruchaga
7         Héctor Enrique
8    Julio Olarticoechea
Name: Nombre, dtype: object

<class 'pandas.core.series.Series'>


### Ejercicio 5

* Mostrar un dataframe con el nombre y el número de todos los jugadores con número de camiseta par

In [7]:
df_par = df[["Nombre", "Número"]][df["Número"] % 2 == 0]
print(df_par)

                 Nombre  Número
0          Nery Pumpido      18
4        Sergio Batista       2
5        Ricardo Giusti      14
7        Héctor Enrique      12
8   Julio Olarticoechea      16
10       Diego Maradona      10


### Ejercicio 6

* Importar con pandas el dataset **'data/US Presidential Election Results - ResultsByTurnout.csv'**


* Mirar qué tipo de datos hay en cada columna y si hay valores nulos

In [9]:
df = pd.read_csv("data/US Presidential Election Results - ResultsByTurnout.csv")


In [16]:
print(df.dtypes)
print(df.isna().sum())

ElectionYear             int64
Turnout(%)             float64
TotalVotes              object
TotalElectoralVotes      int64
ElectoralVotesToWin      int64
dtype: object
ElectionYear           0
Turnout(%)             0
TotalVotes             0
TotalElectoralVotes    0
ElectoralVotesToWin    0
dtype: int64


### Ejercicio 7

* ¿En qué año se registró el mayor porcentaje de participación (Turnout)? ¿Y el mínimo?

In [18]:
print(df["Turnout(%)"].max())
print(df["Turnout(%)"].min())

82.6
6.3


### Ejercicio 8

* Convertir la columna TotalVotes  que es de tipo 'object' a tipo numérico. Para ello es necesario eliminar las comas que indican miles. 

**Ayuda:** aplicar los métodos str.replace(...) y luego .astype(...) sobre la serie TotalVotes

In [26]:
print(df["TotalVotes"].dtype)
print(df["TotalVotes"].str.replace(",", "").astype("float"))
df["TotalVotes"] = df["TotalVotes"].str.replace(",", "").astype("float")

object
0         39624.0
1         28300.0
2         66841.0
3         75142.0
4        143029.0
5        192691.0
6        278786.0
7        112370.0
8        108359.0
9        365833.0
10      1153779.0
11      1293973.0
12      1503534.0
13      2411808.0
14      2703659.0
15      2879184.0
16      3161830.0
17      4056647.0
18      4685561.0
19      4031887.0
20      5722440.0
21      6467678.0
22      8418659.0
23      9219477.0
24     10060145.0
25     11383320.0
26     12068037.0
27     13936957.0
28     13997426.0
29     13525002.0
30     14889239.0
31     15048834.0
32     18536585.0
33     26765180.0
34     29097107.0
35     36807012.0
36     39751898.0
37     45647699.0
38     49902113.0
39     47977063.0
40     48793535.0
41     61751942.0
42     62021328.0
43     68832482.0
44     70639284.0
45     73199998.0
46     77744030.0
47     81531584.0
48     86509678.0
49     92653233.0
50     91594686.0
51    104423923.0
52     96277634.0
53    105421423.0
54    122295345.0
55 

### Ejercicio 9

* Generar una nueva columna que contenga la cantidad de gente empadronada (ElectoralRoll). Calcularlo a partir del número total de votos registrados (TotalVotes) y el porcentaje de participación (Turnout(%))

In [ ]:
df

ElectionYear  Turnout(%)   TotalVotes  TotalElectoralVotes  \
0           1788        11.6       39,624                   69   
1           1792         6.3       28,300                  132   
2           1796        20.1       66,841                  138   
3           1800        32.3       75,142                  138   
4           1804        23.8      143,029                  176   
5           1808        36.8      192,691                  175   
6           1812        40.4      278,786                  217   
7           1816        16.9      112,370                  217   
8           1820        10.1      108,359                  232   
9           1824        26.9      365,833                  261   
10          1828        57.3    1,153,779                  261   
11          1832        57.0    1,293,973                  286   
12          1836        56.5    1,503,534                  294   
13          1840        80.3    2,411,808                  294   
14          1844        79.2    2,703,659                  275   
15          1848        72.8    2,879,184                  290   
16          1852        69.5    3,161,830                  296   
17          1856        79.4    4,056,647                  296   
18          1860        81.8    4,685,561                  303   
19          1864        76.3    4,031,887                  233   
20          1868        80.9    5,722,440                  294   
21          1872        72.1    6,467,678                  352   
22          1876        82.6    8,418,659                  369   
23          1880        80.5    9,219,477                  369   
24          1884        78.2   10,060,145                  401   
25          1888        80.5   11,383,320                  401   
26          1892        75.8   12,068,037                  444   
27          1896        79.6   13,936,957                  447   
28          1900        73.7   13,997,426                  447   
29          1904        65.5   13,525,002                  476   
30          1908        65.7   14,889,239                  483   
31          1912        59.0   15,048,834                  531   
32          1916        61.8   18,536,585                  531   
33          1920        49.2   26,765,180                  531   
34          1924        48.9   29,097,107                  531   
35          1928        56.9   36,807,012                  531   
36          1932        56.9   39,751,898                  531   
37          1936        61.0   45,647,699                  531   
38          1940        62.4   49,902,113                  531   
39          1944        55.9   47,977,063                  531   
40          1948        52.2   48,793,535                  531   
41          1952        62.3   61,751,942                  531   
42          1956        60.2   62,021,328                  531   
43          1960        63.8   68,832,482                  537   
44          1964        62.8   70,639,284                  538   
45          1968        62.5   73,199,998                  538   
46          1972        56.2   77,744,030                  538   
47          1976        54.8   81,531,584                  538   
48          1980        54.2   86,509,678                  538   
49          1984        55.2   92,653,233                  538   
50          1988        52.8   91,594,686                  538   
51          1992        58.1  104,423,923                  538   
52          1996        51.7   96,277,634                  538   
53          2000        54.2  105,421,423                  538   
54          2004        60.1  122,295,345                  538   
55          2008        61.6  131,313,820                  538   
56          2012        58.6  129,085,410                  538   
57          2016        60.1  136,669,276                  538   
58          2020        66.2  158,383,403                  538   

    ElectoralVotesToWin  
0                

### Ejercicio 10

* ¿En qué año se registró por primera vez más del 50% de participación?

In [33]:
df["ElectoralVote"] = (df["TotalVotes"] / df["Turnout(%)"]).astype("int")
df.head()

ElectionYear  Turnout(%)  TotalVotes  TotalElectoralVotes  \
0          1788        11.6     39624.0                   69   
1          1792         6.3     28300.0                  132   
2          1796        20.1     66841.0                  138   
3          1800        32.3     75142.0                  138   
4          1804        23.8    143029.0                  176   

   ElectoralVotesToWin  ElectoralVote  
0                   35           3415  
1                   66           4492  
2                   69           3325  
3                   69           2326  
4                   88           6009

### Ejercicio 11

* ¿Cuál fue el máximo, mímino, promedio y desvio estandar en el nivel de participación durante siglo XX?

In [39]:
df[(df["ElectionYear"] >= 1900) & (df["ElectionYear"] < 2000)][["Turnout(%)"]].describe()

Turnout(%)
count   25.000000
mean    58.548000
std      5.780003
min     48.900000
25%     54.800000
50%     58.100000
75%     62.400000
max     73.700000