In [4]:
import numpy as np

In [5]:
# Creating arrays
arr1 = np.array([1, 2, 3])
print(arr1)  # Output: [1 2 3]

arr2 = np.zeros((2, 3))
print(arr2)  # Output: [[0. 0. 0.]
             #          [0. 0. 0.]]

arr3 = np.ones((2, 3))
print(arr3)  # Output: [[1. 1. 1.]
             #          [1. 1. 1.]]

arr4 = np.arange(0, 10, 2)
print(arr4)  # Output: [0 2 4 6 8]

# Reshaping arrays
arr5 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr5.reshape((2, 3)))  # Output: [[1 2 3]
                            #          [4 5 6]]

arr6 = np.transpose(arr5)
print(arr6)  # Output: [[1 3 5]
             #          [2 4 6]]

# Mathematical operations
arr7 = np.array([1, 2, 3])
arr8 = np.array([4, 5, 6])

arr9 = np.add(arr7, arr8)
print(arr9)  # Output: [5 7 9]

arr10 = np.subtract(arr8, arr7)
print(arr10)  # Output: [3 3 3]

arr11 = np.multiply(arr7, arr8)
print(arr11)  # Output: [ 4 10 18]

arr12 = np.divide(arr8, arr7)
print(arr12)  # Output: [4.  2.5 2. ]

arr13 = np.dot(arr7, arr8)
print(arr13)  # Output: 32

# Statistical operations
arr14 = np.array([1, 2, 3, 4, 5])
print(np.mean(arr14))  # Output: 3.0
print(np.median(arr14))  # Output: 3.0
print(np.std(arr14))  # Output: 1.41421356
print(np.var(arr14))  # Output: 2.0

# Array indexing and slicing
arr15 = np.array([1, 2, 3, 4, 5])
print(arr15[2])  # Output: 3
print(arr15[1:3])  # Output: [2 3]
print(arr15[:3])  # Output: [1 2 3]
print(arr15[3:])  # Output: [4 5]


[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]
[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
32
3.0
3.0
1.4142135623730951
2.0
3
[2 3]
[1 2 3]
[4 5]


In [7]:
l = [3, 5, 10, 7]
a = np.array(l)
print(a)
b = np.arange(0, 10, 2)
print(b)

[ 3  5 10  7]
[0 2 4 6 8]


In [11]:
# Reemplazar todos los números impares por el número $-1$
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2[arr2%2==1] = -1
print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:
#A partir de los array 1D `x` e `y`, crear un array 1D `z` que sea el resultado de eliminar en `x` los elementos presentes en `y`.
# - ver la función [*setdiff1d*](https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html)
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = np.setdiff1d(x, y)
z

array([1, 2, 3, 4])

In [16]:
# Definir una función que obtiene los elementos de una matriz que sean mayores a 10 y multiplos de 3
def m10_mult3(X):
    X1 = X[(X>20)&(X%3==0)]
    return X1
A = np.arange(100).reshape(5,-1)

print(m10_mult3(A))

[21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90
 93 96 99]


In [17]:
def sum_m7_m9(r):
    ### Completa con tu código aquí:
    return r[(r < 100) & (r % 7 == 0) & (r % 9 == 0)].sum()
    ###
    
a = np.arange(1, 200)

sum_m7_m9(a)

63

In [35]:
# Crear una función que calcule la media movil con una ventana de largo 3.

# **pista:**
# - $$SMA = \frac{A_{n-2} + A_{n-1} + A_{n}}{3}$$
# - Método [*cumsum*](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

a = np.random.randint(10, size=10)
a.sort()
# print(a)

def mov_avg(a, n=3):
    b = np.cumsum(a)
    b[n:] = b[n:] - b[:-n]
    return b[n-1:]/n

print(a)
print(np.cumsum(a))
print(mov_avg(a))

[0 0 1 2 3 4 5 8 8 9]
[ 0  0  1  3  6 10 15 23 31 40]
[0.33333333 1.         2.         3.         4.         5.66666667
 7.         8.33333333]
